spring.application.name=san-gabriel-webapi

# =============================================
# Datasource - PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/UsuariosDB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=notificaciones

# =============================================
# Azure Service Bus
# =============================================
azure.servicebus.connection-string=Endpoint=sb://sangabriel.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=nwbmCDYozDN2bxy2qhADJWp/mUoyf5ECC+ASbDfTV60=
azure.servicebus.topic-name=notificaciones
azure.servicebus.subscription-name=notificaciones-san-gabriel
