apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  db-username: postgres
  db-password: admin
  db-name: auth_db
  jwt-secret: "YmFzZS02NC1lbmNvZGVkLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1hdXRoZW50aWNhdGlvbg=="
